### ISSUE TITLE
Broken URL's in readme

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-dapps-docs#9]
Setting up an Environment
Creating a Basic Dapp
Creating a Messaging Dapp
Adding a User Interface
Introducing the Dapp SDK
Creating a Custom Sidechain
Creating a Reddit Dapp
Debugging Dapps

Those links does not exists.

**Comment by MaxKK** [comment]
The .md files in this repository are only the "source code" texts for our Documentation section on our website.   

https://lisk.io/documentation?i=lisk-docs/README
